version: '3'

services:
  i2b2-2web:
    image: i2b2/i2b2-web:p1
    ports:
      - "80:80"
      - "443:443"
    command: /run-httpd.sh localhost
    networks:
      - i2b2net
    depends_on:
      - i2b2-wildfly
  i2b2-wildfly:
    image: i2b2/i2b2-wildfly:0.1
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - i2b2net
    depends_on:
      - i2b2-pg
  i2b2-pg:
    image: i2b2/i2b2-pg:p1
    ports:
      - "5432:5432"
    networks:
      - i2b2net
    
networks: 
    i2b2net:
       driver: bridge
